<?php
/**
 * Generates a .l10n.php translation file from a .po file.
 * WordPress 6.5+ prefers this format over .mo for performance.
 *
 * Usage:
 *   php tools/generate_l10n_php.php
 */

if (php_sapi_name() !== 'cli') { echo "CLI only.\n"; exit(1); }

$po_file  = dirname(__DIR__) . '/wp-content/themes/artroplasti/languages/artroplasti-en_GB.po';
$out_file = dirname(__DIR__) . '/wp-content/themes/artroplasti/languages/artroplasti-en_GB.l10n.php';

if (!file_exists($po_file)) {
    echo "ERROR: .po file not found: {$po_file}\n"; exit(1);
}

function parse_po(string $file): array {
    $content = file_get_contents($file);
    $entries = [];
    $msgid   = null;
    $msgstr  = null;
    $in      = null;

    foreach (explode("\n", $content) as $line) {
        $line = rtrim($line);
        if (str_starts_with($line, 'msgid "')) {
            if ($msgid !== null && $msgstr !== null) {
                $entries[] = [$msgid, $msgstr];
            }
            $msgid  = stripcslashes(substr($line, 7, -1));
            $msgstr = null;
            $in     = 'id';
        } elseif (str_starts_with($line, 'msgstr "')) {
            $msgstr = stripcslashes(substr($line, 8, -1));
            $in     = 'str';
        } elseif (str_starts_with($line, '"') && str_ends_with($line, '"')) {
            $cont = stripcslashes(substr($line, 1, -1));
            if ($in === 'id')  $msgid  .= $cont;
            if ($in === 'str') $msgstr .= $cont;
        } else {
            $in = null;
        }
    }
    if ($msgid !== null && $msgstr !== null) {
        $entries[] = [$msgid, $msgstr];
    }
    return $entries;
}

$entries = parse_po($po_file);

// Separate header from translations
$messages = [];
$meta_header = '';
foreach ($entries as [$id, $str]) {
    if ($id === '') {
        $meta_header = $str;
        continue;
    }
    if ($str !== '') {
        $messages[$id] = $str;
    }
}

echo "Parsed " . count($messages) . " translations.\n";

// Generate .l10n.php in the format WordPress expects
// Format: return ['messages' => [...], 'plural-forms' => '...', 'language' => '...'];
$plural_forms = 'nplurals=2; plural=(n != 1);';
if (preg_match('/Plural-Forms:\s*(.+)/', $meta_header, $m)) {
    $plural_forms = trim($m[1]);
}

$php = "<?php\n";
$php .= "// This file is auto-generated by tools/generate_l10n_php.php\n";
$php .= "// Do not edit manually — edit artroplasti-en_GB.po and regenerate.\n";
$php .= "return [\n";
$php .= "    'domain'       => 'artroplasti',\n";
$php .= "    'language'     => 'en_GB',\n";
$php .= "    'plural-forms' => '" . addslashes($plural_forms) . "',\n";
$php .= "    'messages'     => [\n";

foreach ($messages as $id => $str) {
    $php .= "        " . var_export($id, true) . " => " . var_export($str, true) . ",\n";
}

$php .= "    ],\n";
$php .= "];\n";

file_put_contents($out_file, $php);
echo "Written: {$out_file}\n";
echo "Done.\n";
